### ISSUE TITLE
KeydropAutocode won't work !

### ISSUE THREAD

**Issue by CuppyTheCup** [r3ge/KeydropAutocode#1]
When I try to run the main.exe it just closes and if I try to use slovakia.bat , it throws out this error 
![image](https://user-images.githubusercontent.com/88633468/183363971-9ff4246f-045b-4b13-a2cb-99519f44e6e5.png)

**Comment by r3ge** [comment]
Looks like [keydrop](https://key-drop.com/en/) updated their site.
We will update the selector shortly.

**Comment by r3ge** [comment]
Error has been fixed, if your still having this problem make sure the cookies are valid and that your up to date
