### ISSUE TITLE
Its crashes when open main.exe

### ISSUE THREAD

**Issue by Vonsia** [r3ge/KeydropAutocode#2]
its automatically opens google then closing itself and google

**Comment by r3ge** [comment]
Do you have the v2 of the app ?

**Comment by Vonsia** [comment]
yes i have

**Comment by r3ge** [comment]
> yes i have

Update the bot token & the path of chrome in config.js using notepad
Then send a screenshot of it

**Comment by Vonsia** [comment]
![image](https://user-images.githubusercontent.com/110897325/183635631-d120ef4b-3943-4011-8a7d-063c50d2015e.png)
updated path

**Comment by r3ge** [comment]
> ![image](https://user-images.githubusercontent.com/110897325/183635631-d120ef4b-3943-4011-8a7d-063c50d2015e.png) updated path

run slovakia.bat and send error your getting

**Comment by Vonsia** [comment]
> > ![resim](https://user-images.githubusercontent.com/110897325/183635631-d120ef4b-3943-4011-8a7d-063c50d2015e.png)güncellenmiş yol
> 
> slovakia.bat'ı çalıştırın ve aldığınız hatayı gönderin

![image](https://user-images.githubusercontent.com/110897325/183839332-3e86c116-75a9-46c0-ba94-e8171a2fc8d3.png)
i got this error

**Comment by Vonsia** [comment]
oh and now its says token invalid but i refreshed again and it still says same

**Comment by Vonsia** [comment]
![image](https://user-images.githubusercontent.com/110897325/183840281-e07dfc62-e755-49cf-a73b-6d9afef06996.png)

i already refreshed my token few times

**Comment by r3ge** [comment]
> ![image](https://user-images.githubusercontent.com/110897325/183840281-e07dfc62-e755-49cf-a73b-6d9afef06996.png)
> 
> i already refreshed my token few times

Refresh token again
